#!/bin/bash
export DISPLAY="${DISPLAY:-:0}"
export XAUTHORITY="${XAUTHORITY:-$HOME/.Xauthority}"
export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/run/user/1000}"

# Disable sandboxing
export GSK_RENDERER=cairo
export GDK_DEBUG=gl-disable  
export GLYCIN_USE_SANDBOX=0

exec /usr/bin/chrultrabook-tools "$@"
